# ============================================================
# PROJECT: RNA-Seq AML
# SCRIPT 02 — GLOBAL PCA D0 + D14
# ============================================================
#
# Purpose:
#   1. Load the master CPM matrix 
#   2. Load Metadata.xlsx
#   3. Transform CPM to log2(CPM + 1)
#   4. Perform global PCA with D0 + D14
#   5. Identify each sample by Day
#   6. Connect D0 -> D14 for each patient
#   7. Save PCA matrix, metadata, and figure
#
# ============================================================


# ============================================================
# 1. LOAD REQUIRED PACKAGES
# ============================================================

library(readxl)
library(ggplot2)


# ============================================================
# 2. DEFINE BASE DIRECTORY
# ============================================================

# Change this path to the location of your RNA-seq analysis project.
#
# Example:
# base_dir <- "/path/to/RNAseq_Analysis"

base_dir <- "YOUR_PROJECT_PATH/RNAseq_Analysis"


# ============================================================
# 3. DEFINE DIRECTORIES
# ============================================================

papers_dir <- file.path(
  base_dir,
  "Papers"
)

paper1_dir <- file.path(
  papers_dir,
  "Paper_1"
)

paper1_data <- file.path(
  paper1_dir,
  "data"
)

paper1_objects <- file.path(
  paper1_dir,
  "objects"
)

paper1_figures <- file.path(
  paper1_dir,
  "figures"
)


# ============================================================
# 4. DEFINE INPUT FILES
# ============================================================

# Master CPM matrix without ATRA samples.
#
# This file should be generated by the previous script.

cpm_file <- file.path(
  paper1_objects,
  "Paper1_master_CPM.rds"
)

metadata_file <- file.path(
  papers_dir,
  "Metadata.xlsx"
)


# ============================================================
# 5. DEFINE FIGURE NAME
# ============================================================

# Change this name according to the final figure designation
# used in the manuscript.

figure_name <- "NAME_OF_THE_FIGURE"


# ============================================================
# 6. CHECK INPUT FILES
# ============================================================

if (!file.exists(cpm_file)) {
  
  stop(
    paste0(
      "CPM matrix not found:\n",
      cpm_file
    )
  )
  
}


if (!file.exists(metadata_file)) {
  
  stop(
    paste0(
      "Metadata.xlsx not found:\n",
      metadata_file
    )
  )
  
}


# ============================================================
# 7. LOAD MASTER CPM MATRIX
# ============================================================

master_CPM <- readRDS(
  cpm_file
)


cat("\n============================================\n")
cat("MASTER CPM MATRIX\n")
cat("============================================\n")


cat("\nDimensions:\n")
print(dim(master_CPM))


# ============================================================
# 8. IDENTIFY ANNOTATION COLUMNS
# ============================================================

annotation_columns <- c(
  "gene_id",
  "gene_name",
  "gene_biotype",
  "gene_source",
  "seqname",
  "start",
  "end",
  "strand"
)

annotation_columns <- intersect(
  annotation_columns,
  colnames(master_CPM)
)


# ============================================================
# 9. IDENTIFY SAMPLE COLUMNS
# ============================================================

sample_columns <- setdiff(
  colnames(master_CPM),
  annotation_columns
)


cat("\nNumber of samples:\n")
print(length(sample_columns))


cat("\nSamples:\n")
print(sample_columns)


# ============================================================
# 10. LOAD METADATA
# ============================================================

metadata <- read_excel(
  metadata_file
)

metadata <- as.data.frame(
  metadata
)


cat("\n============================================\n")
cat("METADATA\n")
cat("============================================\n")


cat("\nAvailable columns:\n")
print(colnames(metadata))


# ============================================================
# 11. CHECK REQUIRED COLUMNS
# ============================================================

required_columns <- c(
  "Sample_ID",
  "Day"
)

missing_columns <- setdiff(
  required_columns,
  colnames(metadata)
)

if (length(missing_columns) > 0) {
  
  stop(
    paste0(
      "Missing columns in Meta.xlsx: ",
      paste(
        missing_columns,
        collapse = ", "
      )
    )
  )
  
}


# ============================================================
# 12. IDENTIFY PATIENT COLUMN
# ============================================================

# The metadata may contain either:
#
#   "Patient_number"
#
# or:
#
#   "Patient"
#
# The available column is identified explicitly here.

if ("Patient_number" %in% colnames(metadata)) {
  
  patient_column <- "Patient_number"
  
} else if ("Patient" %in% colnames(metadata)) {
  
  patient_column <- "Patient"
  
} else {
  
  stop(
    "No patient identification column was found."
  )
  
}


cat("\nColumn used for longitudinal pairing:\n")
print(patient_column)


# ============================================================
# 13. STANDARDIZE METADATA
# ============================================================

metadata$Sample_ID <- trimws(
  as.character(
    metadata$Sample_ID
  )
)

metadata$Day <- trimws(
  as.character(
    metadata$Day
  )
)

metadata$Patient <- trimws(
  as.character(
    metadata[[patient_column]]
  )
)


# ============================================================
# 14. CHECK DUPLICATES
# ============================================================

if (anyDuplicated(metadata$Sample_ID) > 0) {
  
  duplicated_ids <- unique(
    metadata$Sample_ID[
      duplicated(metadata$Sample_ID)
    ]
  )
  
  stop(
    paste0(
      "Duplicated Sample_ID in metadata: ",
      paste(
        duplicated_ids,
        collapse = ", "
      )
    )
  )
  
}


# ============================================================
# 15. CHECK MATRIX SAMPLES AGAINST METADATA
# ============================================================

missing_metadata <- setdiff(
  sample_columns,
  metadata$Sample_ID
)

if (length(missing_metadata) > 0) {
  
  stop(
    paste0(
      "The following samples from the matrix are not present ",
      "in Meta.xlsx:\n",
      paste(
        missing_metadata,
        collapse = ", "
      )
    )
  )
  
}


# ============================================================
# 16. ORGANIZE METADATA IN THE SAME ORDER AS THE MATRIX
# ============================================================

metadata_pca <- metadata[
  match(
    sample_columns,
    metadata$Sample_ID
  ),
  ,
  drop = FALSE
]


# Verify sample order

stopifnot(
  identical(
    metadata_pca$Sample_ID,
    sample_columns
  )
)


# ============================================================
# 17. CHECK D0 AND D14
# ============================================================

invalid_day <- setdiff(
  unique(metadata_pca$Day),
  c("D0", "D14")
)

if (length(invalid_day) > 0) {
  
  stop(
    paste0(
      "Unexpected values in the Day column: ",
      paste(
        invalid_day,
        collapse = ", "
      )
    )
  )
  
}


cat("\n============================================\n")
cat("SAMPLE DISTRIBUTION\n")
cat("============================================\n")


print(
  table(
    metadata_pca$Day
  )
)


# ============================================================
# 18. EXTRACT EXPRESSION MATRIX
# ============================================================

master_CPM <- master_CPM[
  ,
  sample_columns,
  drop = FALSE
]


# Ensure numeric values

master_CPM <- as.data.frame(
  lapply(
    master_CPM,
    function(x) {
      as.numeric(
        as.character(x)
      )
    }
  ),
  check.names = FALSE
)


# ============================================================
# 19. TRANSFORM TO log2(CPM + 1)
# ============================================================

master_log2CPM <- log2(
  master_CPM + 1
)


# ============================================================
# 20. REMOVE GENES WITH ZERO VARIANCE
# ============================================================
#
# Genes with constant expression across all samples
# do not contribute to the PCA.
#
# ============================================================

gene_variance <- apply(
  master_log2CPM,
  1,
  var,
  na.rm = TRUE
)

variable_genes <- gene_variance > 0


cat("\n============================================\n")
cat("GENES USED IN PCA\n")
cat("============================================\n")


cat(
  "\nTotal genes:",
  nrow(master_log2CPM),
  "\n"
)

cat(
  "Genes with variance > 0:",
  sum(variable_genes),
  "\n"
)


master_log2CPM_pca <- master_log2CPM[
  variable_genes,
  ,
  drop = FALSE
]


# ============================================================
# 21. PREPARE MATRIX FOR PCA
# ============================================================
#
# prcomp:
#   rows = samples
#   columns = genes
#
# ============================================================

pca_matrix <- t(
  as.matrix(
    master_log2CPM_pca
  )
)


# ============================================================
# 22. PCA
# ============================================================

pca <- prcomp(
  pca_matrix,
  center = TRUE,
  scale. = FALSE
)


# ============================================================
# 23. EXPLAINED VARIANCE
# ============================================================

variance_explained <- (
  pca$sdev^2 /
    sum(pca$sdev^2)
) * 100


cat("\n============================================\n")
cat("EXPLAINED VARIANCE\n")
cat("============================================\n")


cat(
  "\nPC1:",
  round(
    variance_explained[1],
    2
  ),
  "%\n"
)


cat(
  "PC2:",
  round(
    variance_explained[2],
    2
  ),
  "%\n"
)


# ============================================================
# 24. CREATE PCA DATA FRAME
# ============================================================

pca_coordinates <- data.frame(
  Sample_ID = rownames(pca$x),
  PC1 = pca$x[, 1],
  PC2 = pca$x[, 2],
  stringsAsFactors = FALSE
)


# Add metadata

pca_coordinates <- merge(
  pca_coordinates,
  metadata_pca,
  by = "Sample_ID",
  sort = FALSE
)


# Reorder according to PCA sample order

pca_coordinates <- pca_coordinates[
  match(
    rownames(pca$x),
    pca_coordinates$Sample_ID
  ),
  ,
  drop = FALSE
]


rownames(pca_coordinates) <- NULL


# ============================================================
# 25. DEFINE DAY AS FACTOR
# ============================================================

pca_coordinates$Day <- factor(
  pca_coordinates$Day,
  levels = c(
    "D0",
    "D14"
  )
)


# ============================================================
# 26. CHECK LONGITUDINAL PAIRING
# ============================================================

cat("\n============================================\n")
cat("PATIENT PAIRING\n")
cat("============================================\n")


patient_day_table <- table(
  pca_coordinates$Patient,
  pca_coordinates$Day
)

print(
  patient_day_table
)


# ============================================================
# 27. SAVE PCA OBJECT
# ============================================================

saveRDS(
  pca,
  file.path(
    paper1_objects,
    "Paper1_master_PCA.rds"
  )
)


# ============================================================
# 28. SAVE PCA COORDINATES
# ============================================================

write.csv(
  pca_coordinates,
  file.path(
    paper1_data,
    "Paper1_master_PCA_coordinates.csv"
  ),
  row.names = FALSE
)


saveRDS(
  pca_coordinates,
  file.path(
    paper1_objects,
    "Paper1_master_PCA_coordinates.rds"
  )
)


# ============================================================
# 29. SAVE EXPLAINED VARIANCE
# ============================================================

pca_variance <- data.frame(
  PC = paste0(
    "PC",
    seq_along(
      variance_explained
    )
  ),
  variance_explained = variance_explained
)


write.csv(
  pca_variance,
  file.path(
    paper1_data,
    "Paper1_master_PCA_variance.csv"
  ),
  row.names = FALSE
)


# ============================================================
# 30. PCA — D0 + D14 WITH PAIRED LINES
# ============================================================

# Colors

color_D0 <- "#164A8A"
color_D14 <- "#63CFC3"
color_line <- "grey40"


pca_plot <- ggplot(
  pca_coordinates,
  aes(
    x = PC1,
    y = PC2
  )
) +
  
  # ----------------------------------------------------------
# Line connecting D0 -> D14 for each patient
# ----------------------------------------------------------

geom_line(
  aes(
    group = Patient
  ),
  color = color_line,
  linewidth = 0.4,
  alpha = 0.8
) +
  
  # ----------------------------------------------------------
# D0 and D14 points
# ----------------------------------------------------------

geom_point(
  aes(
    color = Day
  ),
  shape = 16,
  size = 3.2
) +
  
  # ----------------------------------------------------------
# Day colors
# ----------------------------------------------------------

scale_color_manual(
  values = c(
    "D0" = color_D0,
    "D14" = color_D14
  )
) +
  
  # ----------------------------------------------------------
# Labels
# ----------------------------------------------------------

labs(
  title = "Global gene expression",
  
  subtitle = paste0(
    "Number of genes analyzed: ",
    sum(variable_genes)
  ),
  
  x = paste0(
    "PC1 (",
    round(
      variance_explained[1],
      1
    ),
    "%)"
  ),
  
  y = paste0(
    "PC2 (",
    round(
      variance_explained[2],
      1
    ),
    "%)"
  ),
  
  color = "Day"
) +
  
  # ----------------------------------------------------------
# Theme
# ----------------------------------------------------------

theme_classic(
  base_size = 11
) +
  
  theme(
    
    # Figure background
    
    plot.background = element_rect(
      fill = "white",
      color = NA
    ),
    
    # Plot background
    
    panel.background = element_rect(
      fill = "grey95",
      color = "white",
      linewidth = 0.35
    ),
    
    # Major grid lines
    
    panel.grid.major = element_line(
      color = "white",
      linewidth = 0.35
    ),
    
    # Minor grid lines
    
    panel.grid.minor = element_line(
      color = "white",
      linewidth = 0.20
    ),
    
    # Main title
    
    plot.title = element_text(
      face = "bold",
      hjust = 0,
      size = 14
    ),
    
    # Subtitle
    
    plot.subtitle = element_text(
      hjust = 0,
      size = 9.5,
      color = "grey30"
    ),
    
    # Axis titles
    
    axis.title = element_text(
      size = 10
    ),
    
    # Axis numbers
    
    axis.text = element_text(
      size = 8.5,
      color = "grey20"
    ),
    
    # Thin axis lines
    
    axis.line = element_line(
      color = "white",
      linewidth = 0.35
    ),
    
    # Thin axis ticks
    
    axis.ticks = element_line(
      color = "grey20",
      linewidth = 0.35
    ),
    
    # Smaller legend
    
    legend.title = element_text(
      size = 9
    ),
    
    legend.text = element_text(
      size = 8
    ),
    
    # White legend background
    
    legend.background = element_rect(
      fill = "white",
      color = NA
    ),
    
    legend.key = element_rect(
      fill = "white",
      color = NA
    ),
    
    legend.position = "right"
  )


# ============================================================
# 31. DISPLAY PCA
# ============================================================

print(
  pca_plot
)


# ============================================================
# 32. SAVE FIGURE
# ============================================================

ggsave(
  filename = file.path(
    paper1_figures,
    paste0(
      figure_name,
      ".pdf"
    )
  ),
  plot = pca_plot,
  width = 8,
  height = 5,
  units = "in"
)


ggsave(
  filename = file.path(
    paper1_figures,
    paste0(
      figure_name,
      ".png"
    )
  ),
  plot = pca_plot,
  width = 8,
  height = 5,
  units = "in",
  dpi = 300
)


# ============================================================
# END OF SCRIPT 02
# ============================================================