# ============================================================
# PROJECT: RNA-Seq AML
# SCRIPT 03 — GLOBAL DESeq2 D0 vs D14
# ============================================================
#
# Purpose:
#   1. Load the master RAW count matrix
#   2. Load Metadata.xlsx
#   3. Maintain the 32 analyzed samples
#   4. Structure the paired design:
#        ~ Patient + Day
#   5. Compare D14 vs D0
#   6. Save the DESeq2 object
#   7. Save complete results
#   8. Save DEGs filtered by adjusted p-value and |log2FC|
#
#
# ============================================================


# ============================================================
# 1. LOAD REQUIRED PACKAGES
# ============================================================

library(readxl)
library(DESeq2)


# ============================================================
# 2. DEFINE BASE DIRECTORY
# ============================================================

# Change this path to the location of your RNA-seq analysis project.
#
# Example:
# base_dir <- "/path/to/RNAseq_Analysis"

base_dir <- "YOUR_PROJECT_PATH/RNAseq_Analysis"


# ============================================================
# 3. DEFINE DIRECTORIES
# ============================================================

papers_dir <- file.path(
  base_dir,
  "Papers"
)

paper1_dir <- file.path(
  papers_dir,
  "Paper_1"
)

paper1_data <- file.path(
  paper1_dir,
  "data"
)

paper1_objects <- file.path(
  paper1_dir,
  "objects"
)


# ============================================================
# 4. DEFINE INPUT FILES
# ============================================================

# Master RAW count matrix without ATRA samples.
#
# This file should be generated by the previous script.

raw_file <- file.path(
  paper1_objects,
  "Paper1_master_raw.rds"
)

metadata_file <- file.path(
  papers_dir,
  "Metadata.xlsx"
)


# ============================================================
# 5. CHECK INPUT FILES
# ============================================================

if (!file.exists(raw_file)) {
  
  stop(
    paste0(
      "RAW count matrix not found:\n",
      raw_file
    )
  )
  
}


if (!file.exists(metadata_file)) {
  
  stop(
    paste0(
      "Metadata.xlsx not found:\n",
      metadata_file
    )
  )
  
}


# ============================================================
# 6. LOAD MASTER RAW MATRIX
# ============================================================

master_raw <- readRDS(
  raw_file
)


cat("\n============================================\n")
cat("MASTER RAW COUNT MATRIX\n")
cat("============================================\n")


cat(
  "\nMatrix dimensions:\n"
)

print(
  dim(master_raw)
)


# ============================================================
# 7. IDENTIFY ANNOTATION COLUMNS
# ============================================================

annotation_columns <- c(
  "gene_id",
  "gene_name",
  "gene_biotype",
  "gene_source",
  "seqname",
  "start",
  "end",
  "strand"
)

annotation_columns <- intersect(
  annotation_columns,
  colnames(master_raw)
)


# ============================================================
# 8. IDENTIFY SAMPLE COLUMNS
# ============================================================

sample_columns <- setdiff(
  colnames(master_raw),
  annotation_columns
)


cat(
  "\nNumber of samples in matrix:\n"
)

print(
  length(sample_columns)
)


cat(
  "\nSamples:\n"
)

print(
  sample_columns
)


# ============================================================
# 9. LOAD METADATA
# ============================================================

metadata <- read_excel(
  metadata_file
)

metadata <- as.data.frame(
  metadata
)


cat("\n============================================\n")
cat("METADATA\n")
cat("============================================\n")


cat(
  "\nAvailable columns:\n"
)

print(
  colnames(metadata)
)


# ============================================================
# 10. CHECK REQUIRED COLUMNS
# ============================================================

required_columns <- c(
  "Sample_ID",
  "Day"
)

missing_columns <- setdiff(
  required_columns,
  colnames(metadata)
)

if (length(missing_columns) > 0) {
  
  stop(
    paste0(
      "Missing columns in Metadata.xlsx: ",
      paste(
        missing_columns,
        collapse = ", "
      )
    )
  )
  
}


# ============================================================
# 11. IDENTIFY PATIENT COLUMN
# ============================================================

if ("Patient_number" %in% colnames(metadata)) {
  
  patient_column <- "Patient_number"
  
} else if ("Patient" %in% colnames(metadata)) {
  
  patient_column <- "Patient"
  
} else {
  
  stop(
    "No patient identification column was found."
  )
  
}


cat(
  "\nColumn used for longitudinal pairing:\n"
)

print(
  patient_column
)


# ============================================================
# 12. STANDARDIZE METADATA
# ============================================================

metadata$Sample_ID <- trimws(
  as.character(
    metadata$Sample_ID
  )
)

metadata$Day <- trimws(
  as.character(
    metadata$Day
  )
)

metadata$Patient <- trimws(
  as.character(
    metadata[[patient_column]]
  )
)


# ============================================================
# 13. CHECK DUPLICATES
# ============================================================

if (anyDuplicated(metadata$Sample_ID) > 0) {
  
  duplicated_ids <- unique(
    metadata$Sample_ID[
      duplicated(metadata$Sample_ID)
    ]
  )
  
  stop(
    paste0(
      "Duplicated Sample_ID in metadata: ",
      paste(
        duplicated_ids,
        collapse = ", "
      )
    )
  )
  
}


# ============================================================
# 14. CHECK SAMPLES
# ============================================================

missing_metadata <- setdiff(
  sample_columns,
  metadata$Sample_ID
)

if (length(missing_metadata) > 0) {
  
  stop(
    paste0(
      "Samples from the matrix missing in Metadata.xlsx:\n",
      paste(
        missing_metadata,
        collapse = ", "
      )
    )
  )
  
}


# ============================================================
# 15. ORGANIZE METADATA IN THE SAME ORDER AS THE MATRIX
# ============================================================

metadata_deseq <- metadata[
  match(
    sample_columns,
    metadata$Sample_ID
  ),
  ,
  drop = FALSE
]


stopifnot(
  identical(
    metadata_deseq$Sample_ID,
    sample_columns
  )
)


# ============================================================
# 16. CHECK D0 AND D14
# ============================================================

invalid_day <- setdiff(
  unique(metadata_deseq$Day),
  c("D0", "D14")
)

if (length(invalid_day) > 0) {
  
  stop(
    paste0(
      "Unexpected values in the Day column: ",
      paste(
        invalid_day,
        collapse = ", "
      )
    )
  )
  
}


cat("\n============================================\n")
cat("DAY DISTRIBUTION\n")
cat("============================================\n")


print(
  table(
    metadata_deseq$Day
  )
)


# ============================================================
# 17. CHECK LONGITUDINAL PAIRING
# ============================================================

patient_day_table <- table(
  metadata_deseq$Patient,
  metadata_deseq$Day
)


cat("\n============================================\n")
cat("PATIENT PAIRING\n")
cat("============================================\n")


print(
  patient_day_table
)


# Patients with both D0 and D14

paired_patients <- rownames(
  patient_day_table
)[
  patient_day_table[, "D0"] > 0 &
    patient_day_table[, "D14"] > 0
]


cat(
  "\nNumber of patients with D0 + D14:\n"
)

print(
  length(paired_patients)
)


# ============================================================
# 18. PREPARE COUNT MATRIX
# ============================================================

count_matrix <- master_raw[
  ,
  sample_columns,
  drop = FALSE
]


# Ensure numeric values

count_matrix <- as.data.frame(
  lapply(
    count_matrix,
    function(x) {
      as.numeric(
        as.character(x)
      )
    }
  ),
  check.names = FALSE
)


# ============================================================
# 19. USE gene_id AS ROW NAMES
# ============================================================

if (!"gene_id" %in% colnames(master_raw)) {
  
  stop(
    "The gene_id column was not found in the matrix."
  )
  
}


gene_ids <- as.character(
  master_raw$gene_id
)


# Check duplicated gene IDs

duplicated_gene_ids <- duplicated(
  gene_ids
)


cat(
  "\nDuplicated genes:",
  sum(duplicated_gene_ids),
  "\n"
)


if (any(duplicated_gene_ids)) {
  
  stop(
    "Duplicated gene_id values were detected. Resolve them before running DESeq2."
  )
  
}


rownames(count_matrix) <- gene_ids


# ============================================================
# 20. PREPARE COL_DATA
# ============================================================

col_data <- metadata_deseq

rownames(col_data) <- col_data$Sample_ID


col_data$Patient <- factor(
  col_data$Patient
)

col_data$Day <- factor(
  col_data$Day,
  levels = c(
    "D0",
    "D14"
  )
)


# ============================================================
# 21. FINAL CHECKS
# ============================================================

stopifnot(
  identical(
    colnames(count_matrix),
    rownames(col_data)
  )
)


stopifnot(
  all(
    count_matrix >= 0
  )
)


stopifnot(
  all(
    count_matrix == floor(count_matrix)
  )
)


cat("\n============================================\n")
cat("FINAL CHECKS\n")
cat("============================================\n")


cat(
  "\nSamples:",
  ncol(count_matrix),
  "\n"
)


cat(
  "Genes:",
  nrow(count_matrix),
  "\n"
)


cat(
  "Patients:",
  nlevels(col_data$Patient),
  "\n"
)


cat(
  "D0:",
  sum(col_data$Day == "D0"),
  "\n"
)


cat(
  "D14:",
  sum(col_data$Day == "D14"),
  "\n"
)


# ============================================================
# 22. CREATE DESeq2 OBJECT
# ============================================================

dds <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = col_data,
  design = ~ Patient + Day
)


# ============================================================
# 23. RUN DESeq2
# ============================================================

dds <- DESeq(
  dds
)


# ============================================================
# 24. D14 VS D0 RESULT
# ============================================================

res <- results(
  dds,
  contrast = c(
    "Day",
    "D14",
    "D0"
  )
)


# ============================================================
# 25. ORGANIZE RESULTS
# ============================================================

res_df <- as.data.frame(
  res
)

res_df$gene_id <- rownames(
  res_df
)


# ============================================================
# 26. ADD gene_name ANNOTATION
# ============================================================

if ("gene_name" %in% colnames(master_raw)) {
  
  gene_annotation <- data.frame(
    gene_id = as.character(
      master_raw$gene_id
    ),
    gene_name = as.character(
      master_raw$gene_name
    ),
    stringsAsFactors = FALSE
  )
  
  res_df <- merge(
    res_df,
    gene_annotation,
    by = "gene_id",
    all.x = TRUE,
    sort = FALSE
  )
  
}


# ============================================================
# 27. ORDER RESULTS BY adjusted p-value
# ============================================================

res_df_ordered <- res_df[
  order(
    res_df$padj,
    na.last = TRUE
  ),
  ,
  drop = FALSE
]


# ============================================================
# 28. DESeq2 SUMMARY
# ============================================================

cat("\n============================================\n")
cat("DESeq2 — D14 VS D0\n")
cat("============================================\n")


cat(
  "\nGenes with available p-value:",
  sum(
    !is.na(res_df$pvalue)
  ),
  "\n"
)


cat(
  "Genes with padj < 0.05:",
  sum(
    res_df$padj < 0.05,
    na.rm = TRUE
  ),
  "\n"
)


cat(
  "Genes upregulated in D14:",
  sum(
    res_df$padj < 0.05 &
      res_df$log2FoldChange > 0,
    na.rm = TRUE
  ),
  "\n"
)


cat(
  "Genes downregulated in D14:",
  sum(
    res_df$padj < 0.05 &
      res_df$log2FoldChange < 0,
    na.rm = TRUE
  ),
  "\n"
)


# ============================================================
# 29. DEFINE DEGs
# ============================================================
#
# Criteria:
#   padj < 0.05
#   |log2FoldChange| >= 1
#
# ============================================================

deg_df <- res_df[
  !is.na(res_df$padj) &
    res_df$padj < 0.05 &
    abs(res_df$log2FoldChange) >= 1,
  ,
  drop = FALSE
]


# Order DEGs by adjusted p-value

deg_df <- deg_df[
  order(
    deg_df$padj,
    na.last = TRUE
  ),
  ,
  drop = FALSE
]


cat("\n============================================\n")
cat("DEGs — padj < 0.05 | |log2FC| >= 1\n")
cat("============================================\n")


cat(
  "\nNumber of DEGs:",
  nrow(deg_df),
  "\n"
)


cat(
  "\nTop 20 DEGs:\n"
)


print(
  head(
    deg_df,
    20
  )
)


# ============================================================
# 30. SAVE DESeq2 OBJECT
# ============================================================

saveRDS(
  dds,
  file.path(
    paper1_objects,
    "Paper1_master_DESeq2_D14_vs_D0.rds"
  )
)


# ============================================================
# 31. SAVE COMPLETE RESULTS
# ============================================================
#
# This file will be used later for GSEA.
#
# ============================================================

write.csv(
  res_df,
  file.path(
    paper1_data,
    "Paper1_master_DESeq2_D14_vs_D0_all.csv"
  ),
  row.names = FALSE
)


# ============================================================
# 32. SAVE RESULTS ORDERED BY adjusted p-value
# ============================================================

write.csv(
  res_df_ordered,
  file.path(
    paper1_data,
    "Paper1_master_DESeq2_D14_vs_D0_all_ordered.csv"
  ),
  row.names = FALSE
)


# ============================================================
# 33. SAVE DEGs
# ============================================================

write.csv(
  deg_df,
  file.path(
    paper1_data,
    "Paper1_master_DEGs_D14_vs_D0.csv"
  ),
  row.names = FALSE
)


# ============================================================
# 34. FINAL
# ============================================================

cat("\n============================================\n")
cat("SCRIPT 03 — DESeq2 COMPLETED\n")
cat("============================================\n")


cat(
  "\nComparison: D14 vs D0\n"
)


cat(
  "Design: ~ Patient + Day\n"
)


cat(
  "Paired patients:",
  length(paired_patients),
  "\n"
)


cat(
  "Samples:",
  ncol(count_matrix),
  "\n"
)


cat(
  "Genes in matrix:",
  nrow(count_matrix),
  "\n"
)


cat(
  "Genes with p-value:",
  sum(
    !is.na(res_df$pvalue)
  ),
  "\n"
)


cat(
  "DEGs (padj < 0.05 | |log2FC| >= 1):",
  nrow(deg_df),
  "\n"
)


cat(
  "\nResults saved in:\n",
  paper1_data,
  "\n"
)


cat(
  "\n============================================\n"
)

cat(
  "END OF SCRIPT 03\n"
)

cat(
  "============================================\n"
)

# ============================================================
# END OF SCRIPT 03
# ============================================================