################################################################################
# SCRIPT 05 — VOLCANO PLOT
# Paper 1 — Global transcriptomic landscape
################################################################################

# This script generates a volcano plot for the global longitudinal comparison
# between diagnosis (D0) and day 14 (D14) after treatment.
#
# The analysis uses the complete DESeq2 results generated in Script 03.
# Differential expression was performed using the paired design:
#
#   ~ Patient + Day
#
# The contrast evaluated is:
#
#   Day D14 vs D0
#
# The volcano plot displays:
#
#   X-axis: log2 Fold Change
#   Y-axis: -log10(adjusted p-value)
#
# Significance criteria:
#
#   padj < 0.05
#   |log2FC| >= 1


################################################################################
# 1. LOAD PACKAGES
################################################################################

library(DESeq2)
library(tidyverse)
library(ggplot2)
library(writexl)


################################################################################
# 2. DEFINE PATHS
################################################################################

# Change this path to your local project directory
base_dir <- "YOUR_PROJECT_PATH/RNAseq_Analysis"

papers_dir <- file.path(
  base_dir,
  "Papers"
)

paper1_dir <- file.path(
  papers_dir,
  "Paper_1"
)

data_dir <- file.path(
  paper1_dir,
  "data"
)

objects_dir <- file.path(
  paper1_dir,
  "objects"
)

figures_dir <- file.path(
  paper1_dir,
  "figures"
)

dir.create(
  figures_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


################################################################################
# 3. DEFINE FILE NAMES
################################################################################

# Change only this name if the final figure name needs to be changed
figure_name <- "NAME_OF_THE_FIGURE"

de_results_file <- file.path(
  data_dir,
  "Paper1_master_DESeq2_D14_vs_D0_all.csv"
)


################################################################################
# 4. LOAD DESEQ2 RESULTS
################################################################################

# Complete DESeq2 results generated by Script 03

res_df <- read.csv(
  de_results_file,
  stringsAsFactors = FALSE
)


################################################################################
# 5. DEFINE SIGNIFICANCE THRESHOLDS
################################################################################

padj_cutoff <- 0.05

log2fc_cutoff <- 1


################################################################################
# 6. PREPARE DATA FOR VOLCANO PLOT
################################################################################

volcano_df <- res_df %>%
  filter(
    !is.na(log2FoldChange),
    !is.na(padj),
    padj > 0
  ) %>%
  mutate(
    
    neg_log10_padj = -log10(padj),
    
    significance = case_when(
      
      padj < padj_cutoff &
        log2FoldChange >= log2fc_cutoff ~
        "Upregulated",
      
      padj < padj_cutoff &
        log2FoldChange <= -log2fc_cutoff ~
        "Downregulated",
      
      TRUE ~
        "Not significant"
    )
  )


################################################################################
# 7. CHECK NUMBER OF GENES
################################################################################

cat("\n")
cat("============================================\n")
cat("VOLCANO PLOT\n")
cat("D14 vs D0\n")
cat("============================================\n")

cat(
  "Total genes with valid padj:",
  nrow(volcano_df),
  "\n"
)

cat(
  "Significant genes (padj < 0.05):",
  sum(
    volcano_df$padj < padj_cutoff,
    na.rm = TRUE
  ),
  "\n"
)

cat(
  "Significant DEGs (padj < 0.05 & |log2FC| >= 1):",
  sum(
    volcano_df$padj < padj_cutoff &
      abs(volcano_df$log2FoldChange) >= log2fc_cutoff,
    na.rm = TRUE
  ),
  "\n"
)

cat(
  "Upregulated:",
  sum(
    volcano_df$padj < padj_cutoff &
      volcano_df$log2FoldChange >= log2fc_cutoff,
    na.rm = TRUE
  ),
  "\n"
)

cat(
  "Downregulated:",
  sum(
    volcano_df$padj < padj_cutoff &
      volcano_df$log2FoldChange <= -log2fc_cutoff,
    na.rm = TRUE
  ),
  "\n"
)

cat("============================================\n")
cat("\n")


################################################################################
# 8. CREATE VOLCANO PLOT
################################################################################

volcano_plot <- ggplot(
  volcano_df,
  aes(
    x = log2FoldChange,
    y = neg_log10_padj
  )
) +
  
  # All genes
  geom_point(
    aes(
      color = significance
    ),
    alpha = 0.6,
    size = 1.5
  ) +
  
  # Adjusted p-value threshold
  geom_hline(
    yintercept = -log10(padj_cutoff),
    linetype = "dashed",
    linewidth = 0.3
  ) +
  
  # Fold-change thresholds
  geom_vline(
    xintercept = c(
      -log2fc_cutoff,
      log2fc_cutoff
    ),
    linetype = "dashed",
    linewidth = 0.3
  ) +
  
  labs(
    title = "Global gene expression",
    subtitle = "D14 vs D0",
    x = "log2 Fold Change",
    y = "-log10 (adjusted p-value)",
    color = NULL
  ) +
  
  scale_color_manual(
    values = c(
      "Upregulated" = "#8B1E3F",
      "Downregulated" = "#164A8A",
      "Not significant" = "grey70"
    )
  ) +
  
  theme_bw() +
  
  theme(
    
    plot.title = element_text(
      size = 14,
      face = "bold"
    ),
    
    plot.subtitle = element_text(
      size = 9,
      color = "grey40"
    ),
    
    axis.title = element_text(
      size = 8
    ),
    
    axis.text = element_text(
      size = 8
    ),
    
    legend.position = "right",
    
    panel.grid.major = element_line(
      color = "white"
    ),
    
    panel.grid.minor = element_line(
      color = "white"
    ),
    
    panel.background = element_rect(
      fill = "grey95"
    ),
    
    panel.border = element_rect(
      color = "white",
      fill = NA,
      linewidth = 0.8
    ),
    
    plot.background = element_rect(
      fill = "white",
      color = NA
    )
  )


################################################################################
# 9. DISPLAY VOLCANO PLOT
################################################################################

print(volcano_plot)


################################################################################
# 10. SAVE VOLCANO PLOT — PNG
################################################################################

ggsave(
  filename = file.path(
    figures_dir,
    paste0(
      figure_name,
      ".png"
    )
  ),
  plot = volcano_plot,
  width = 10,
  height = 6,
  dpi = 300
)


################################################################################
# 11. SAVE VOLCANO PLOT — PDF
################################################################################

ggsave(
  filename = file.path(
    figures_dir,
    paste0(
      figure_name,
      ".pdf"
    )
  ),
  plot = volcano_plot,
  width = 10,
  height = 6
)


################################################################################
# 12. SAVE VOLCANO DATA
################################################################################

write.csv(
  volcano_df,
  file.path(
    data_dir,
    "Paper1_master_Volcano_D14_vs_D0.csv"
  ),
  row.names = FALSE
)

write_xlsx(
  volcano_df,
  file.path(
    data_dir,
    "Paper1_master_Volcano_D14_vs_D0.xlsx"
  )
)


################################################################################
# 13. EXPORT SIGNIFICANT DEGs
################################################################################

significant_DEGs <- volcano_df %>%
  filter(
    !is.na(padj),
    padj < padj_cutoff,
    abs(log2FoldChange) >= log2fc_cutoff
  ) %>%
  arrange(padj)


write.csv(
  significant_DEGs,
  file.path(
    data_dir,
    "Paper1_master_DEGs_padj0.05_log2FC1.csv"
  ),
  row.names = FALSE
)

write_xlsx(
  significant_DEGs,
  file.path(
    data_dir,
    "Paper1_master_DEGs_padj0.05_log2FC1.xlsx"
  )
)


################################################################################
# 14. FINAL SUMMARY
################################################################################

cat("\n")
cat("============================================\n")
cat("SCRIPT 05 — VOLCANO PLOT COMPLETED\n")
cat("============================================\n")

cat(
  "Comparison: D14 vs D0\n"
)

cat(
  "Adjusted p-value cutoff:",
  padj_cutoff,
  "\n"
)

cat(
  "Absolute log2FC cutoff:",
  log2fc_cutoff,
  "\n\n"
)

cat(
  "PNG:\n",
  file.path(
    figures_dir,
    paste0(
      figure_name,
      ".png"
    )
  ),
  "\n\n"
)

cat(
  "PDF:\n",
  file.path(
    figures_dir,
    paste0(
      figure_name,
      ".pdf"
    )
  ),
  "\n\n"
)

cat(
  "Volcano data:\n",
  file.path(
    data_dir,
    "Paper1_master_Volcano_D14_vs_D0.csv"
  ),
  "\n\n"
)

cat(
  "Significant DEGs:",
  nrow(significant_DEGs),
  "\n"
)

cat(
  "Upregulated:",
  sum(
    significant_DEGs$log2FoldChange >=
      log2fc_cutoff
  ),
  "\n"
)

cat(
  "Downregulated:",
  sum(
    significant_DEGs$log2FoldChange <=
      -log2fc_cutoff
  ),
  "\n"
)

# ============================================================
# END OF SCRIPT 05
# ============================================================